ravitandon90/ThreeHundredDaysOfCode-BE

- README.md
- deployments/local/docker-compose.yml
- deployments/scripts/init.sql
- master/src/main/java/com/code/master/data/UserNotification.java
- master/src/main/java/com/code/master/data/UserNotificationRepository.java
- master/src/main/java/com/code/master/service/MasterController.java
The following fixes were applied -
1. UserNotification.java - use consistent CamelCase variables
2. UserNotificationRepository.java - fix exceptions while building
3. MasterController.java - Fixed err:  no mapping provided for get post calls Fixed by defining GetMappint(path = <valid-path>)
4. init.sql - incorrect column type (fixed varchar for user_notification)
The following updates were made-
1. docker-compose.yml - uses environment variables (defined in README.md) for- a. using custom docker tags b. custom volume paths
2. consistent CamelCase variables in java files
> [UserNotification] Bug fixes, readme update and consistent naming

- proddata/data/max_consecutive_ones/Python/Driver.py
- proddata/data/max_consecutive_ones/Python/Solution.py
> Add driver program and solution (in Python) for the problem Max Consecutive Ones

- proddata/data/intersection_of_two_arrays/Python/Driver.py
> Add driver program in Python for the problem Intersection of Two Arrays

- proddata/data/4sum/Python/Driver.py
- proddata/data/intersection_of_two_arrays/Python/Driver.py
- proddata/data/max_consecutive_ones/Python/Driver.py
In the 4Sum driver, `line.strip()[-1]` would've failed to catch inputs greater than or equal to 10.
In the other 2 programs, the code was failing for empty array parsing. Hence the check:
`return [] if array[0] == "" else list(
map(int, array))`
> Fix bugs and tackle edge cases in input data

- proddata/data/find_the_town_judge/Python/Driver.py
- proddata/data/keys_and_rooms/Python/Driver.py
- proddata/data/merge_sorted_array/Python/Driver.py
- proddata/data/network_delay_time/Python/Driver.py
- proddata/data/number_of_provinces/Python/Driver.py
- proddata/data/reorder_routes_to_make_all_paths_lead_to_the_city_zero/Python/Driver.py
The programs have been tested locally and are running as expected.
> Add more driver programs in Python

- proddata/data/monotonic_array/Python/Driver.py
- proddata/data/running_sum_of_1d_array/Python/Driver.py
- proddata/data/shifting_letters/Python/Driver.py
- proddata/data/sort_array_by_increasing_frequency/Python/Driver.py
- proddata/data/sort_array_by_parity/Python/Driver.py
- proddata/data/third_maximum_number/Python/Driver.py
All the programs have been tested locally and are running as expected.
> Add driver programs in Python for 6 problems from 2nd September to 8th September

- proddata/data/check_if_it_is_a_straight_line/Python/Driver.py
- proddata/data/kids_with_the_greatest_number_of_candies/Python/Driver.py
- proddata/data/move_zeroes/Python/Driver.py
- proddata/data/plus_one/Python/Driver.py
- proddata/data/product_of_array_except_self/Python/Driver.py
- proddata/data/rotate_array/Python/Driver.py
All the programs have been tested locally and are running as expected.
> Add driver programs in Python for 6 problems from 24th August to 1st September

- proddata/data/create_target_array_in_the_given_order/Python/Driver.py
- proddata/data/decompress_run_length_encoded_list/Python/Driver.py
- proddata/data/h_index/Python/Driver.py
- proddata/data/kth_missing_positive_number/Python/Driver.py
- proddata/data/longest_continuous_increasing_subsequence/Python/Driver.py
- proddata/data/number_of_good_pairs/Python/Driver.py
The programs have been tested locally and are running as expected.
> Add driver programs in Python for problems from 18th August to 23rd August

- proddata/data/binary_search/Python/Driver.py
- proddata/data/find_minimum_in_rotated_sorted_array/Python/Driver.py
- proddata/data/fizz_buzz/Python/Driver.py
- proddata/data/search_insert_position/Python/Driver.py
- proddata/data/sort_an_array/Python/Driver.py
- proddata/data/sort_colors/Python/Driver.py
The programs have been tested locally and are running as expected.
> Add driver programs in Python for problems from 16th Jan, 2023 to 21st Jan, 2023

- proddata/data/asteroid_collision/Solution.hpp
- proddata/data/asteroid_collision/driver.cpp
This is the driver program of asteroid collision.Kindly tell me where there is wrong I will correct it and learn.
ThankYou
> Pratyakshadrivers

- proddata/data/asteroid_collision/Python/Driver.py
- proddata/data/minimum_difference_between_largest_and_smallest_value_in_three_moves/Python/Driver.py
- proddata/data/reorder_data_in_log_files/Python/Driver.py
- proddata/data/sorting_the_sentence/Python/Driver.py
- proddata/data/text_justification/Python/Driver.py
- proddata/data/valid_anagram/Python/Driver.py
All codes have been tested locally, and are running as expected.
> Add driver programs in Python for problems from 22nd Jan, 2023 to 27th Jan, 2023

- proddata/data/decode_string/Python/Driver.py
- proddata/data/defanging_an_ip_address/Python/Driver.py
- proddata/data/implement_strstr/Python/Driver.py
- proddata/data/make_the_string_great/Python/Driver.py
- proddata/data/maximum_nesting_depth_of_the_parentheses/Python/Driver.py
- proddata/data/minimum_add_to_make_parentheses_valid/Python/Driver.py
All the driver codes have been tested locally and are running as expected.
> Add driver code in Python for 6 problems between 29th Jan, 2023 to 5th Feb, 2023

- proddata/data/buddy_strings/Python/Driver.py
- proddata/data/check_if_word_equals_summation_of_two_words/Python/Driver.py
- proddata/data/excel_sheet_column_title/Python/Driver.py
- proddata/data/longest_common_prefix/Python/Driver.py
- proddata/data/longest_happy_string/Python/Driver.py
- proddata/data/shuffle_string/Python/Driver.py
All codes have been tested locally, and are running as expected.
> Add driver programs in Python from 6th Feb, 2023 to 11th Feb, 2023

- proddata/data/goat_latin/Python/Driver.py
- proddata/data/longest_substring_without_repeating_characters/Python/Driver.py
- proddata/data/longest_uncommon_subsequence_i/Python/Driver.py
- proddata/data/ransom_note/Python/Driver.py
- proddata/data/reverse_string/Python/Driver.py
- proddata/data/valid_palindrome/Python/Driver.py
All codes have been tested locally and are running as expected.
> Add Python driver programs from 13th Feb, 2023 to 18th Feb, 2023

- proddata/data/best_time_to_buy_and_sell_stock/Python/Driver.py
- proddata/data/can_place_flowers/Python/Driver.py
- proddata/data/container_with_most_water/Python/Driver.py
- proddata/data/contains_duplicate/Python/Driver.py
- proddata/data/continuous_subarray_sum/Python/Driver.py
- proddata/data/first_unique_character_in_a_string/Python/Driver.py
- proddata/data/letter_tile_possibilities/Python/Driver.py
- proddata/data/maximum_score_from_removing_stones/Python/Driver.py
- proddata/data/maximum_swap/Python/Driver.py
- proddata/data/maximum_units_on_a_truck/Python/Driver.py
Driver programs for 10 problems added. The programs have been tested locally and are running as expected.
> Add driver programs for problems from 31st October to 9th November

- proddata/data/check_if_it_is_a_straight_line/Javascript/Driver.js
- proddata/data/check_if_it_is_a_straight_line/Javascript/Solution.js
> Add driver code for check if it is a straight line in Javascript

- proddata/data/move_zeroes/Javascript/Driver.js
- proddata/data/move_zeroes/Javascript/Solution.js
> Add driver code for move zeroes program in Javascript

- proddata/Javascript/helper.js
- proddata/data/contains_duplicate/Javascript/Driver.js
- Helper function in Javascript
- Driver program for contains_duplicate in JS.
> Add driver program for contains_duplicate in js and retain helper fn

- proddata/data/create_target_array_in_the_given_order/Go/Driver.go
- proddata/data/decompress_run_length_encoded_list/Go/Driver.go
- proddata/data/h_index/Go/Driver.go
- proddata/data/kth_missing_positive_number/Go/Driver.go
- proddata/data/longest_continuous_increasing_subsequence/Go/Driver.go
- proddata/data/max_consecutive_ones/Go/Driver.go
- proddata/data/number_of_good_pairs/Go/Driver.go
Currently, the helper functions are present in the driver programs. This will be changed in a later PR with a separate helper file for the helper methods.
> Add driver programs in Go for problems from 17th August to 23rd August

- master/src/main/java/com/code/master/common/TagProblemToCompanyRequest.java
- master/src/main/java/com/code/master/data/CompanyQuestion.java
- master/src/main/java/com/code/master/data/CompanyQuestionareRepository.java
- master/src/main/java/com/code/master/service/MasterController.java
Added API to tag a problem to a comany , this is maintained in a separate table 
Added a new json key in the method get problem by ID in the master controller
To-Do 
1.Add a unique key constraint on company and porblem 
2. Modifications might be needed to add the company's data in problem description class may be , but it is a matter of discussion.
> Changes for tagging a problem to a company
